name: ac_connectivity
description: Stateful connectivity_plus extended with Internet connectivity
version: 0.3.0
repository: https://github.com/anthochamp/flutter-connectivity

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  ac_dart_essentials: ^0.2.1
  ac_inet_connectivity_checker: ^0.2.0
  ac_flutter_essentials: ^0.1.0
  async: ^2.10.0
  connectivity_plus: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  ac_lints: ^0.4.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
