name: Validate

on: 
  push:
    branches: [ 'main', 'v[0-9]+', 'v[0-9]+.[0-9]+' ]
    tags-ignore: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/flutter-validate.yml@bbf9b11828958cc3b840dbe4051e8493c6dfa2a6
